DROP TABLE IF EXISTS exercises;

CREATE TABLE exercises (
    id SERIAL PRIMARY KEY,
    movement VARCHAR(255), 
    target_area VARCHAR(255),
    push_pull_legs VARCHAR(255)
);

INSERT INTO exercises (movement, target_area, push_pull_legs) VALUES
('Bench Press', 'Chest', 'Push'),
('Overhead Press', 'Shoulders', 'Push'),
('Push-Ups', 'Chest', 'Push'),
('Dumbbell Flyes', 'Chest', 'Push'),
('Tricep Dips', 'Triceps', 'Push'),
('Incline Bench Press', 'Upper Chest', 'Push'),
('Dumbbell Shoulder Press', 'Shoulders', 'Push'),
('Close-Grip Bench Press', 'Chest', 'Push'),
('Front Raise', 'Shoulders', 'Push'),
('Chest Press Machine', 'Chest', 'Push'),
('Arnold Press', 'Shoulders', 'Push'),
('Cable Crossover', 'Chest', 'Push'),
('Tricep Kickbacks', 'Triceps', 'Push'),
('Decline Bench Press', 'Chest', 'Push'),
('Lateral Raises', 'Shoulders', 'Push'),
('Pec Deck Machine', 'Chest', 'Push'),
('Tricep Pushdowns', 'Triceps', 'Push'),
('Shoulder Press Machine', 'Shoulders', 'Push'),
('Diamond Push-Ups', 'Chest', 'Push'),
('Overhead Tricep Extensions', 'Triceps', 'Push'),
('Pull-Ups', 'Back, Biceps', 'Pull'),
('Barbell Rows', 'Back', 'Pull'),
('Lat Pulldowns', 'Back, Biceps', 'Pull'),
('Face Pulls', 'Upper Back', 'Pull'),
('Chin-Ups', 'Back, Biceps', 'Pull'),
('T-Bar Rows', 'Middle Back', 'Pull'),
('Seated Cable Rows', 'Back', 'Pull'),
('Hammer Curls', 'Biceps', 'Pull'),
('Wide Pull-Ups', 'Back, Biceps', 'Pull'),
('Single-Arm Dumbbell Rows', 'Back', 'Pull'),
('Inverted Rows', 'Back, Biceps', 'Pull'),
('Lat Pushdowns', 'Lats', 'Pull'),
('Kroc Rows', 'Back', 'Pull'),
('Preacher Curls', 'Biceps', 'Pull'),
('Machine Lat Pulldowns', 'Back, Biceps', 'Pull'),
('Shrugs', 'Traps', 'Pull'),
('Close Grip Lat Pulldowns', 'Back, Biceps', 'Pull'),
('Reverse Grip Barbell Rows', 'Upper Back, Biceps', 'Pull'),
('Wide Dumbbell Curls', 'Biceps', 'Pull'),
('Squats', 'Quads', 'Legs'),
('Deadlifts', 'Hamstrings', 'Pull'),
('Leg Press', 'Quads', 'Legs'),
('Lunges', 'Quads', 'Legs'),
('Romanian Deadlifts', 'Hamstrings', 'Pull'),
('Hack Squats', 'Quads', 'Legs'),
('Calf Raises', 'Calves', 'Legs'),
('Step-Ups', 'Quads', 'Legs'),
('Good Mornings', 'Hamstrings', 'Pull'),
('Leg Extensions', 'Quads', 'Legs'),
('Leg Curls', 'Hamstrings', 'Legs'),
('Box Jumps', 'Quads', 'Legs'),
('Walking Lunges', 'Quads', 'Legs'),
('Bulgarian Split Squats', 'Quads', 'Legs'),
('Seated Leg Press', 'Quads', 'Legs'),
('Sumo Deadlifts', 'Hamstrings', 'Pull'),
('Front Squats', 'Quads', 'Legs'),
('Hamstring Curls', 'Hamstrings', 'Legs'),
('Cossack Squats', 'Quads', 'Legs');